.PHONY: clean All

All:
	@echo "----------Building project:[ realloc - Debug ]----------"
	@cd "realloc" && "$(MAKE)" -f  "realloc.mk"
clean:
	@echo "----------Cleaning project:[ realloc - Debug ]----------"
	@cd "realloc" && "$(MAKE)" -f  "realloc.mk" clean
